// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unddxlhlszgzprahjbvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZGR4bGhsc3pnenByYWhqYnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MDg1NDYsImV4cCI6MjA3ODE4NDU0Nn0.yN2uTx-qpfpzhzbG0Duh3grH3NPfHn4FkKyk6GGSB2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});